spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: &connectionUrl jdbc:mysql://${DB_CONNECTION_IP:localhost}:${DB_CONNECTION_PORT:3307}/ing_course_ms?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=UTF-8
    username: &username ${DB_CONNECTION_USERNAME:root}
    password: &password ${DB_CONNECTION_PASSWORD:password}
  jpa:
    hibernate:
      ddl-auto: validate
    database: mysql
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQL57Dialect
    show-sql: true
  liquibase:
    drop-first: false
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true